
on: push
name: Main Workflow
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: ${{ secrets.SONARQUBE_HOST_ON_GCP }}
        login: ${{ secrets.SONARQUBE_TOKEN_ON_GCP }}
        projectBaseDir: "./server"
        projectKey: "test1_java"
        projectName: "test1_java"
#          projectVersion: "v0.0.1"
#        run: sonar-scanner
#           -Dsonar.host.url=${{ secrets.SONARQUBE_HOST_ON_GCP }}
#          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN_ON_GCP }}

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#       - name: Setup sonarqube
#        # run: warchant/setup-sonar-scanner@v1
#         run: | kitabisa/sonarqube-action@master
#           -Dsonar.host.url=${{ secrets.SONARQUBE_HOST_ON_GCP }} 
#           -Dsonar.login=${{ secrets.SONARQUBE_TOKEN_ON_GCP }} 
#           -Dsonar.java.binaries=/server
