on: push
name: Main Workflow
# jobs:
#   sonarQubeTrigger:
#     name: SonarQube Trigger
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
#     - name: SonarQube Scan
#       uses: kitabisa/sonarqube-action@master
# #       with:
# #         host: ${{ secrets.SONARQUBE_HOST_ON_GCP }}
# #         login: ${{ secrets.SONARQUBE_TOKEN_ON_GCP }}
#       run: sonar-scanner
#          -Dsonar.host.url=${{ secrets.SONARQUBE_HOST_ON_GCP }}
#          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN_ON_GCP }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v1
          -Dsonar.host.url=${{ secrets.SONARQUBE_HOST_ON_GCP }} 
          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN_ON_GCP }} 
          -Dsonar.java.binaries=/server
