
on: push
name: Main Workflow
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: ${{ secrets.SONARQUBE_HOST_ON_GCP }}
        login: ${{ secrets.SONARQUBE_TOKEN_ON_GCP }}
        projectBaseDir: "."
        projectKey: "test2_notMaven"
        projectName: "test2_notMaven"
#        env: -Dsonar.java.binaries="."
#        args: . ./env ; docker build -t $IMAGE .
#      env: "-Dsonar.java.binaries=."
